import { caseStudies, getCaseStudyPath } from "@/data/case-studies";
import { about, personalInfo } from "@/data/portfolio";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://yash-ai-portfolio-production.up.railway.app";
export const ogLocale = "en_IN";

export const siteConfig = {
  siteUrl,
  homeUrl: `${siteUrl}/`,
  resumeUrl: `${siteUrl}${personalInfo.resumeUrl}`,
  updatedAt: "2026-09-23T00:00:00.000Z",
  siteName: "Yash Srivastava — Applied AI Engineer",
  title: `${personalInfo.name} — Applied AI Engineer`,
  description: personalInfo.tagline,
  author: personalInfo.name,
  creator: personalInfo.name,
  email: personalInfo.email,
  github: personalInfo.github,
  linkedin: personalInfo.linkedin,
  locale: "en-IN",
  ogLocale,
  ogImage: "/og-image.svg",
  keywords: [
    "Yash Srivastava",
    "Applied AI Engineer",
    "LLM Evaluation",
    "LLM-as-a-Judge",
    "Langfuse",
    "Ragas",
    "OpenTelemetry",
    "Golden Datasets",
    "Prompt Caching",
    "Model Routing",
    "Forward Deployed Engineer",
    "Forward Deployed AI Engineer",
    "Full-Stack Engineer",
    "Backend Engineer",
    "AI Engineer",
    "Platform Engineer",
    "Software Engineer",
    "GenAI Products",
    "Backend Systems",
    "Full-Stack Platform Engineering",
    "API Design",
    "REST APIs",
    "Distributed Systems",
    "AI Observability",
    "AI Governance",
    "AI Gateways",
    "Load Balancing",
    "DevOps",
    "Platform Engineering",
    "CI/CD",
    "Observability",
    "GraphRAG",
    "Knowledge Graph RAG",
    "LightRAG",
    "Graphiti",
    "Multi-Agent Systems",
    "Agentic AI",
    "AI Automation",
    "TypeScript",
    "Node.js",
    "Go",
    "Gin",
    "MCP",
    "MCP Servers",
    "OpenCode",
    "OpenCode Server",
    "Platform Agent Memory",
    "LangChain",
    "LangGraph",
    "FastAPI",
    "Spring Boot",
    "AI Infrastructure",
    "RAG",
    "Full-Stack Development",
  ],
  geo: {
    region: "IN-HR",
    placename: "Gurugram, Haryana, India",
    latitude: 28.4595,
    longitude: 77.0266,
    position: "28.4595;77.0266",
    icbm: "28.4595, 77.0266",
  },
  sameAs: [personalInfo.github, personalInfo.linkedin],
  aboutSummary: about.summary,
} as const;

export const caseStudyPages = caseStudies.map((study) => `${siteUrl}${getCaseStudyPath(study.slug)}`);

/** Home first, then each case study. Consumed by sitemap.ts. */
export const canonicalPages = [siteConfig.homeUrl, `${siteConfig.siteUrl}/work`, ...caseStudyPages];
